color0 
color1
color2 
color3 
color4 
color5 
color6 
color7 
color8 
color9 
color10 
color11 
color12 
color13 
color14 
color15 

cursor                
cursor_text_color     
background            
foreground            
selection_foreground  
selection_background  
active_border_color   
inactive_border_color 
url_color             

active_tab_foreground   
active_tab_background   
inactive_tab_foreground 
inactive_tab_background 
cursor_trail_color      
